name: Linux Tag Build

on:
  workflow_dispatch:

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-linux-build:
    uses: ./.github/workflows/linux-build.yml
    secrets: inherit
    with:
      upload-tag: ${{ github.ref_name }}

  run-linux-package-build:
    needs: run-linux-build
    uses: ./.github/workflows/linux-package-build.yml
    secrets: inherit
    with:
      upload-tag: ${{ github.ref_name }}

  run-linux-release:
    needs:
      - run-linux-build
      - run-linux-package-build
    uses: ./.github/workflows/linux-release.yml
    secrets: inherit
    with:
      upload-tag: ${{ github.ref_name }}
