name: Linux Tag Build

permissions:
  contents: read

on:
  workflow_dispatch:

  push:
    tags:
      - 'latest'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-linux-build:
    uses: ./.github/workflows/linux-build.yml
    secrets: inherit
    with:
      upload-tag: ${{ github.ref_name }}


  run-linux-release:
    needs:
      - run-linux-build

    permissions:
      contents: write

    runs-on: ubuntu-24.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: release
          merge-multiple: true

      - name: Check release files
        run: |
          find release -type f

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            release/**
