name: Build Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - arch: x86_64
            os: ubuntu-24.04

          - arch: arm64
            os: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            clang \
            make \
            git \
            binutils \
            cmake \
            autoconf \
            automake \
            libtool \
            pkg-config \
            perl \
            python3

      - name: Build
        run: |
          ./build.sh

      - name: Package
        run: |
          mkdir -p release/android-lp-tools-${{ github.ref_name }}-linux-${{ matrix.arch }}

          cp bin/* release/android-lp-tools-${{ github.ref_name }}-linux-${{ matrix.arch }}/

          tar -czf \
            android-lp-tools-${{ github.ref_name }}-linux-${{ matrix.arch }}.tar.gz \
            -C release \
            android-lp-tools-${{ github.ref_name }}-linux-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-lp-tools-${{ matrix.arch }}
          path: android-lp-tools-${{ github.ref_name }}-linux-${{ matrix.arch }}.tar.gz


  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: android-lp-tools-*
          path: release
          merge-multiple: true

      - name: Check release files
        run: |
          find release -type f -name "*.tar.gz"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.tar.gz
